// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: system.proto
#ifndef GRPC_system_2eproto__INCLUDED
#define GRPC_system_2eproto__INCLUDED

#include "system.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace userData {

class userDataRequest final {
 public:
  static constexpr char const* service_full_name() {
    return "userData.userDataRequest";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status userRequest(::grpc::ClientContext* context, const ::userData::Cpf& request, ::userData::Data* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userData::Data>> AsyncuserRequest(::grpc::ClientContext* context, const ::userData::Cpf& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userData::Data>>(AsyncuserRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userData::Data>> PrepareAsyncuserRequest(::grpc::ClientContext* context, const ::userData::Cpf& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userData::Data>>(PrepareAsyncuserRequestRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void userRequest(::grpc::ClientContext* context, const ::userData::Cpf* request, ::userData::Data* response, std::function<void(::grpc::Status)>) = 0;
      virtual void userRequest(::grpc::ClientContext* context, const ::userData::Cpf* request, ::userData::Data* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::userData::Data>* AsyncuserRequestRaw(::grpc::ClientContext* context, const ::userData::Cpf& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::userData::Data>* PrepareAsyncuserRequestRaw(::grpc::ClientContext* context, const ::userData::Cpf& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status userRequest(::grpc::ClientContext* context, const ::userData::Cpf& request, ::userData::Data* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userData::Data>> AsyncuserRequest(::grpc::ClientContext* context, const ::userData::Cpf& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userData::Data>>(AsyncuserRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userData::Data>> PrepareAsyncuserRequest(::grpc::ClientContext* context, const ::userData::Cpf& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userData::Data>>(PrepareAsyncuserRequestRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void userRequest(::grpc::ClientContext* context, const ::userData::Cpf* request, ::userData::Data* response, std::function<void(::grpc::Status)>) override;
      void userRequest(::grpc::ClientContext* context, const ::userData::Cpf* request, ::userData::Data* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::userData::Data>* AsyncuserRequestRaw(::grpc::ClientContext* context, const ::userData::Cpf& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::userData::Data>* PrepareAsyncuserRequestRaw(::grpc::ClientContext* context, const ::userData::Cpf& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_userRequest_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status userRequest(::grpc::ServerContext* context, const ::userData::Cpf* request, ::userData::Data* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_userRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_userRequest() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_userRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status userRequest(::grpc::ServerContext* /*context*/, const ::userData::Cpf* /*request*/, ::userData::Data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestuserRequest(::grpc::ServerContext* context, ::userData::Cpf* request, ::grpc::ServerAsyncResponseWriter< ::userData::Data>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_userRequest<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_userRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_userRequest() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::userData::Cpf, ::userData::Data>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::userData::Cpf* request, ::userData::Data* response) { return this->userRequest(context, request, response); }));}
    void SetMessageAllocatorFor_userRequest(
        ::grpc::MessageAllocator< ::userData::Cpf, ::userData::Data>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::userData::Cpf, ::userData::Data>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_userRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status userRequest(::grpc::ServerContext* /*context*/, const ::userData::Cpf* /*request*/, ::userData::Data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* userRequest(
      ::grpc::CallbackServerContext* /*context*/, const ::userData::Cpf* /*request*/, ::userData::Data* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_userRequest<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_userRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_userRequest() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_userRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status userRequest(::grpc::ServerContext* /*context*/, const ::userData::Cpf* /*request*/, ::userData::Data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_userRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_userRequest() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_userRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status userRequest(::grpc::ServerContext* /*context*/, const ::userData::Cpf* /*request*/, ::userData::Data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestuserRequest(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_userRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_userRequest() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->userRequest(context, request, response); }));
    }
    ~WithRawCallbackMethod_userRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status userRequest(::grpc::ServerContext* /*context*/, const ::userData::Cpf* /*request*/, ::userData::Data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* userRequest(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_userRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_userRequest() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::userData::Cpf, ::userData::Data>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::userData::Cpf, ::userData::Data>* streamer) {
                       return this->StreameduserRequest(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_userRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status userRequest(::grpc::ServerContext* /*context*/, const ::userData::Cpf* /*request*/, ::userData::Data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreameduserRequest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::userData::Cpf,::userData::Data>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_userRequest<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_userRequest<Service > StreamedService;
};

}  // namespace userData


#endif  // GRPC_system_2eproto__INCLUDED
