// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: system.proto

#include "system.pb.h"
#include "system.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace userData {

static const char* userDataRequest_method_names[] = {
  "/userData.userDataRequest/userRequest",
};

std::unique_ptr< userDataRequest::Stub> userDataRequest::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< userDataRequest::Stub> stub(new userDataRequest::Stub(channel, options));
  return stub;
}

userDataRequest::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_userRequest_(userDataRequest_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status userDataRequest::Stub::userRequest(::grpc::ClientContext* context, const ::userData::Cpf& request, ::userData::Data* response) {
  return ::grpc::internal::BlockingUnaryCall< ::userData::Cpf, ::userData::Data, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_userRequest_, context, request, response);
}

void userDataRequest::Stub::async::userRequest(::grpc::ClientContext* context, const ::userData::Cpf* request, ::userData::Data* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::userData::Cpf, ::userData::Data, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_userRequest_, context, request, response, std::move(f));
}

void userDataRequest::Stub::async::userRequest(::grpc::ClientContext* context, const ::userData::Cpf* request, ::userData::Data* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_userRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::userData::Data>* userDataRequest::Stub::PrepareAsyncuserRequestRaw(::grpc::ClientContext* context, const ::userData::Cpf& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::userData::Data, ::userData::Cpf, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_userRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::userData::Data>* userDataRequest::Stub::AsyncuserRequestRaw(::grpc::ClientContext* context, const ::userData::Cpf& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncuserRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

userDataRequest::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      userDataRequest_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< userDataRequest::Service, ::userData::Cpf, ::userData::Data, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](userDataRequest::Service* service,
             ::grpc::ServerContext* ctx,
             const ::userData::Cpf* req,
             ::userData::Data* resp) {
               return service->userRequest(ctx, req, resp);
             }, this)));
}

userDataRequest::Service::~Service() {
}

::grpc::Status userDataRequest::Service::userRequest(::grpc::ServerContext* context, const ::userData::Cpf* request, ::userData::Data* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace userData

